name: p6_nivel_digital_obra
description: "P6 · Nivel digital de obra - Actividad No. 5 SENA ADSO"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0
  sensors_plus: ^6.0.1
  geolocator: ^12.0.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  image: ^4.2.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
